<?php

namespace APIBundle\Repository;

/**
 * ArtisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtisteRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByPseudoPart($pseudoPart)
    {

        /*
         * SELECT * FROM Artiste WHERE pseudo LIKE "%PseudoPart%";
         *
         * */

        $qb = $this->createQueryBuilder("a")//a, artiste, artistes, b, ...
        ->where('a.pseudo LIKE :pseudoPart')
            ->setParameter("pseudoPart", "%" . $pseudoPart . "%");

        return $qb->getQuery()->getResult();

    }
}
